# Tic-Tac-Toe Checker

If we were to set up a Tic-Tac-Toe game, we would want to know whether the board's current state is solved, wouldn't we? Our goal is to create a function that will check that for us!

Assume that the board comes in the form of a 3x3 array, where the value is 0 if a spot is empty, 1 if it is an "X", or 2 if it is an "O", like so:

[[0, 0, 1],

 [0, 1, 2],
 
 [2, 1, 0]]
 
### We want our function to return:
   
1. -1 if the board is not yet finished (there are empty spots),
2. -1 if "X" won,
3. 2 if "O" won,
4. 0 if it's a cat's game (i.e. a draw).

You may assume that the board passed in is valid in the context of a game of Tic-Tac-Toe.

In [2]:
import numpy as np

In [265]:
# Generate an empty 3x3 array assume "0" as empty spats
board = np.zeros([3,3])

positions = []
for r in range(3):
    for s in range(3):
        post = r, s
        positions.append(post)
#print(positions)

horiz_pos_0 = positions[:3]; #print(horiz_pos_0)
horiz_pos_1 = positions[3:6]; #print(horiz_pos_1)
horiz_pos_2 = positions[6:9]; #print(horiz_pos_2)

vert_pos_0 = [positions[i] for i in range(0,9,3)]; #print(vert_pos_0)
vert_pos_1 = [positions[i] for i in range(1,9,3)]; #print(vert_pos_1)
vert_pos_2 = [positions[i] for i in range(2,9,3)]; #print(vert_pos_2)

diag_pos_left_right = [positions[i] for i in range(0,9,4)]; #print(diag_pos)
diag_pos_right_left = [positions[i] for i in range(2,8,2)]; #print(diag_pos)

# Choice position player 'X' plays, assume "X" as 1
def get_choice_of_player():
    player_choice = np.random.choice(3), np.random.choice(3)
    return player_choice

board

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [266]:
# player x play, assume "X" as 1
def player_X(board):
    # get player choice of position
    player_spot_X = get_choice_of_player()
    #print(player_spot_X)

    for i in range(3):
        for j in range(3):
            position = i, j
            if board[position] == 0 and position == player_spot_X:
                #print(position)
                board[player_spot_X] = 1
    return board

player_X(board)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.]])

In [267]:
# Choice player 'O' plays, assume "O" as 2
def player_O(board):
    # get player O choice of position
    player_spot_O = get_choice_of_player()
    #print(player_spot_O)

    for i in range(3):
        for j in range(3):
            position = i, j
            if board[position] == 0 and position == player_spot_O:
                #print(position)
                board[player_spot_O] = 2
    return board

player_O(board)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 2.]])

In [268]:
# function to check if there is an empty spots
def check_empty(board):
    empty = []
    for i in range(3):
        for j in range(3):
            position = i, j
            if board[position] == 0:
                empty.append('yes')
    #print(empty)
    if 'yes' in empty:
        #print("There is still an empty space")
        return 'Yes'
    else:
        #print("Board space is filled up")
        return 'No'
check_empty(board)

'Yes'

In [269]:
# if 'X' won
def player_X_won(board):
    game_state_X = []
    if board[vert_pos_0[0]] == board[vert_pos_0[1]] == board[vert_pos_0[2]] == 1:
        game_state_X.append('won')
    elif board[vert_pos_1[0]] == board[vert_pos_1[1]] == board[vert_pos_1[2]] == 1:
        game_state_X.append('won')
    elif board[vert_pos_2[0]] == board[vert_pos_2[1]] == board[vert_pos_2[2]] == 1:
        game_state_X.append('won')
    elif board[horiz_pos_0[0]] == board[horiz_pos_0[1]] == board[horiz_pos_0[2]] == 1:
        game_state_X.append('won')
    elif board[horiz_pos_1[0]] == board[horiz_pos_1[1]] == board[horiz_pos_1[2]] == 1:
        game_state_X.append('won')
    elif board[horiz_pos_2[0]] == board[horiz_pos_2[1]] == board[horiz_pos_2[2]] == 1:
        game_state_X.append('won')
    elif board[diag_pos_left_right[0]] == board[diag_pos_left_right[1]] == board[diag_pos_left_right[2]] == 1:
        game_state_X.append('won')
    elif board[diag_pos_right_left[0]] == board[diag_pos_right_left[1]] == board[diag_pos_right_left[2]] == 1:
        game_state_X.append('won')
    if 'won' in game_state_X:
        return 1
    
# if 'O' won
def player_O_won(board):
    game_state_O = []
    if board[vert_pos_0[0]] == board[vert_pos_0[1]] == board[vert_pos_0[2]] == 2:
        game_state_O.append('won')
    elif board[vert_pos_1[0]] == board[vert_pos_1[1]] == board[vert_pos_1[2]] == 2:
        game_state_O.append('won')
    elif board[vert_pos_2[0]] == board[vert_pos_2[1]] == board[vert_pos_2[2]] == 2:
        game_state_O.append('won')
    elif board[horiz_pos_0[0]] == board[horiz_pos_0[1]] == board[horiz_pos_0[2]] == 2:
        game_state_O.append('won')
    elif board[horiz_pos_1[0]] == board[horiz_pos_1[1]] == board[horiz_pos_1[2]] == 2:
        game_state_O.append('won')
    elif board[horiz_pos_2[0]] == board[horiz_pos_2[1]] == board[horiz_pos_2[2]] == 2:
        game_state_O.append('won')
    elif board[diag_pos_left_right[0]] == board[diag_pos_left_right[1]] == board[diag_pos_left_right[2]] == 2:
        game_state_O.append('won')
    elif board[diag_pos_right_left[0]] == board[diag_pos_right_left[1]] == board[diag_pos_right_left[2]] == 2:
        game_state_O.append('won')
    elif game_state_O == []:
        game_state_O.append('lose')
    if 'won' in game_state_O:
        return 2
    
# if it's a cat's game (i.e. a draw)
def player_draw(board):
    get_game_state_X = player_O_won(board)[0]
    get_game_state_O = player_X_won(board)[0]
    if get_game_state_X == get_game_state_O:
        return 0

In [285]:
board = np.zeros([3,3])
operate = 'Yes'
while operate:
    player_X(board)
    player_O(board)
    operate = check_empty(board)
    if operate == 'No':
        break
print(board)

final = []
final.append(player_X_won(board))
final.append(player_O_won(board))
final
for i in final:
    if i is not None:
        print(i)
if None not in final:
    print(0)

[[1. 2. 2.]
 [2. 2. 1.]
 [2. 1. 2.]]
2


# Below is the complete function for the above problem.

In [317]:
def is_solved(board):
    # Convert board to an array
    board = np.array(board)
    positions = []
    for r in range(3):
        for s in range(3):
            post = r, s
            positions.append(post)
    #print(positions)

    horiz_pos_0 = positions[:3]; #print(horiz_pos_0)
    horiz_pos_1 = positions[3:6]; #print(horiz_pos_1)
    horiz_pos_2 = positions[6:9]; #print(horiz_pos_2)

    vert_pos_0 = [positions[i] for i in range(0,9,3)]; #print(vert_pos_0)
    vert_pos_1 = [positions[i] for i in range(1,9,3)]; #print(vert_pos_1)
    vert_pos_2 = [positions[i] for i in range(2,9,3)]; #print(vert_pos_2)

    diag_pos_left_right = [positions[i] for i in range(0,9,4)]; #print(diag_pos)
    diag_pos_right_left = [positions[i] for i in range(2,8,2)]; #print(diag_pos)
    
    #def check_empty(board):
    empty = []
    for i in range(3):
        for j in range(3):
            position = i, j
            if board[position] == 0:
                empty.append('yes')
    
    game_state_X = []
    if board[vert_pos_0[0]] == board[vert_pos_0[1]] == board[vert_pos_0[2]] == 1:
        game_state_X.append('won')
    elif board[vert_pos_1[0]] == board[vert_pos_1[1]] == board[vert_pos_1[2]] == 1:
        game_state_X.append('won')
    elif board[vert_pos_2[0]] == board[vert_pos_2[1]] == board[vert_pos_2[2]] == 1:
        game_state_X.append('won')
    elif board[horiz_pos_0[0]] == board[horiz_pos_0[1]] == board[horiz_pos_0[2]] == 1:
        game_state_X.append('won')
    elif board[horiz_pos_1[0]] == board[horiz_pos_1[1]] == board[horiz_pos_1[2]] == 1:
        game_state_X.append('won')
    elif board[horiz_pos_2[0]] == board[horiz_pos_2[1]] == board[horiz_pos_2[2]] == 1:
        game_state_X.append('won')
    elif board[diag_pos_left_right[0]] == board[diag_pos_left_right[1]] == board[diag_pos_left_right[2]] == 1:
        game_state_X.append('won')
    elif board[diag_pos_right_left[0]] == board[diag_pos_right_left[1]] == board[diag_pos_right_left[2]] == 1:
        game_state_X.append('won')
    #print(game_state_X)
    
    game_state_O = []
    if board[vert_pos_0[0]] == board[vert_pos_0[1]] == board[vert_pos_0[2]] == 2:
        game_state_O.append('won')
    elif board[vert_pos_1[0]] == board[vert_pos_1[1]] == board[vert_pos_1[2]] == 2:
        game_state_O.append('won')
    elif board[vert_pos_2[0]] == board[vert_pos_2[1]] == board[vert_pos_2[2]] == 2:
        game_state_O.append('won')
    elif board[horiz_pos_0[0]] == board[horiz_pos_0[1]] == board[horiz_pos_0[2]] == 2:
        game_state_O.append('won')
    elif board[horiz_pos_1[0]] == board[horiz_pos_1[1]] == board[horiz_pos_1[2]] == 2:
        game_state_O.append('won')
    elif board[horiz_pos_2[0]] == board[horiz_pos_2[1]] == board[horiz_pos_2[2]] == 2:
        game_state_O.append('won')
    elif board[diag_pos_left_right[0]] == board[diag_pos_left_right[1]] == board[diag_pos_left_right[2]] == 2:
        game_state_O.append('won')
    elif board[diag_pos_right_left[0]] == board[diag_pos_right_left[1]] == board[diag_pos_right_left[2]] == 2:
        game_state_O.append('won')
    elif game_state_O == []:
        game_state_O.append('lose')
    #print(game_state_O)
    
    if 'won' in game_state_X:
        return 1
    elif 'won' in game_state_O:
        return 2
    
    elif 'won' not in game_state_O and 'won' not in game_state_X and 'yes' in empty:
        return -1
    else:
        return 0
        
    
#     final = []
#     final.append(player_X_won(board))
#     final.append(player_O_won(board))
#     final
#     for i in final:
#         if i is not None:
#             print(i)
#     if None not in final:
#         print(0)

In [318]:
board = [[1, 1, 1],
         [0, 2, 2],
         [0, 0, 0]]

In [320]:
board = [[0, 0, 1],
         [0, 1, 2],
         [2, 1, 0]]

In [322]:
board = [[2, 1, 2],
         [2, 1, 1],
         [1, 1, 2]]

In [324]:
board = [[2, 1, 2],
         [2, 1, 1],
         [1, 2, 1]]

In [325]:
is_solved(board)

0